# Generated by Django 3.0.4 on 2020-03-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
